// ignore_for_file: constant_identifier_names, camel_case_types

enum CHECKING_DEVICE { VALID_DEVICE, EXIPRED_DEVICE, INTERNAL_SERVER_ERROR }

enum SIGN_UP_RESULT {
  SUCCESS,
  FAILURE,
  SERVER_ERROR,
  BAD_REQUEST_EMAIL_USED,
  BAD_REQUEST_MISSING_EMAIL,
  BAD_REQUEST_MISSING_USERNAME,
  BAD_REQUEST_MISSING_PASSWORD
}
